# Generated by Django 4.1.3 on 2023-12-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='volume',
            field=models.CharField(max_length=60),
        ),
    ]
